const productData = [
    { productName:'HAVIT HV-G92 Gamepad', category:"electronics", subCategory:"Gaming", harga: 120000 , terjual:130 , discount: 40 , icon:"fa-solid fa-gamepad", images: '../assets/images/product/Frame 611.png', url: 'https://example.com/yoga', },
    { productName:'AK-900 Wired Keyboard', category:"electronics", subCategory:"Computers", harga: 380000 , terjual:120 , discount: 35 , icon:"fa-solid fa-desktop", images: '../assets/images/product/Frame 612.png', url: 'https://example.com/yoga', },
    { productName:'IPS LCD Gaming Monitor', category:"electronics", subCategory:"Computers", harga: 1500000 , terjual:116 , discount: 20 , icon:"fa-solid fa-desktop", images: '../assets/images/product/Frame 613.png', url: 'https://example.com/yoga', },   
    { productName:'S-Series Comfort Chair', category:"Home & Lifestyle", subCategory:"Furniture", harga: 257000 , terjual:71 , discount: 25 , icon:"fa-solid fa-couch", images: '../assets/images/product/Frame 614.png', url: 'https://example.com/yoga', },   
    { productName:'Gucci duffle bag', category:"Woman’s Fashion", subCategory:"Bag", harga: 257000 , terjual:58 , discount: 60 , icon:"fa-solid fa-bag-shopping", images: '../assets/images/product/Frame 609.png', url: 'https://example.com/yoga', },   
    { productName:'ASUS FHD Gaming Laptop', category:"electronics", subCategory:"Computers", harga: 257000 , terjual:56 , discount: 50 , icon:"fa-solid fa-couch", images: '../assets/images/product/Frame 6.png', url: 'https://example.com/yoga', },   
    { productName:'Small BookSelf', category:"Home & Lifestyle", subCategory:"Furniture", harga: 257000 , terjual:36 , discount: 10 , icon:"fa-solid fa-couch", images: '../assets/images/product/Frame 627.png', url: 'https://example.com/yoga', },   
    { productName:'Quilted Satin Jacket', category:"Men’s Fashion", subCategory:"Shirt", harga: 257000 , terjual:10 , discount: 15 , icon:"fa-solid fa-shirt", images: '../assets/images/product/Frame 8.png', url: 'https://example.com/yoga', },   
    { productName:'CANON EOS DSLR Camera', category:"electronics", subCategory:"Camera", harga: 257000 , terjual:181 ,  icon:"fa-solid fa-camera", images: '../assets/images/product/Frame 644.png', url: 'https://example.com/yoga', },   
    { productName:'GP11 Shooter USB Gamepad', category:"electronics", subCategory:"Gaming", harga: 257000 , terjual:146 ,  icon:"fa-solid fa-gamepad", images: '../assets/images/product/Frame 688.png', url: 'https://example.com/yoga', },   
    { productName:'Breed Dry Dog Food', category:"Groceries & Pets", subCategory:"Animal Food", harga: 257000 , terjual:34 ,  icon:"fa-solid fa-bone", images: '../assets/images/product/Frame 60.png', url: 'https://example.com/yoga', },   
    { productName:'The north coat', category:"Woman’s Fashion", subCategory:"Shirt", harga: 257000 , terjual:230 ,  icon:"fa-solid fa-shirt", images: '../assets/images/product/Frame 65.png', url: 'https://example.com/yoga', },   
    { productName:'RGB liquid CPU Cooler', category:"electronics", subCategory:"Computers", harga: 257000 , terjual:173 ,  icon:"fa-solid ffa-desktop", images: '../assets/images/product/Frame 69.png', url: 'https://example.com/yoga', },   
    { productName:'Dumbbell ', category:"Sports & Outdoor", subCategory:"Sports", harga: 257000 , terjual:51 ,  icon:"fa-solid fa-dumbbell", images: '../assets/images/product/Frame 612.png', url: 'https://example.com/yoga', },   
    { productName:'Drug ', category:"Medicine", subCategory:"Medicine", harga: 257000 , terjual:15 ,  icon:"fa-solid fa-pills", images: '../assets/images/product/Frame 612.png', url: 'https://example.com/yoga', },   
];

export default productData;