const productData = [
    { productName:'HAVIT HV-G92 Gamepad', category:"electronics", subCategory:"Gaming", harga: 120000 , terjual:900 , discount: 40 , icon:"fa-solid fa-gamepad", images: '../assets/images/product/Frame 612.png', url: 'https://example.com/yoga', },
    { productName:'AK-900 Wired Keyboard', category:"electronics", subCategory:"Computers", harga: 380000 , terjual:120 , discount: 35 , icon:"fa-solid fa-desktop", images: '../assets/images/product/Frame 614.png', url: 'https://example.com/yoga', },
    { productName:'IPS LCD Gaming Monitor', category:"electronics", subCategory:"Computers", harga: 1500000 , terjual:10 , discount: 20 , icon:"fa-solid fa-desktop", images: '../assets/images/product/Frame 613.png', url: 'https://example.com/yoga', },   
    { productName:'S-Series Comfort Chair ', category:"Home & Lifestyle", subCategory:"Camera", harga: 257000 , terjual:107 ,  icon:"fa-solid fa-camera", images: '../assets/images/product/Frame 612.png', url: 'https://example.com/yoga', },   
    { productName:'S-Series Comfort Chair ', category:"Home & Lifestyle", subCategory:"Phones", harga: 257000 , terjual:25 ,  icon:"fa-solid fa-mobile-screen-button", images: '../assets/images/product/Frame 611.png', url: 'https://example.com/yoga', },   
    { productName:'S-Series Comfort Chair ', category:"Home & Lifestyle", subCategory:"HeadPhones", harga: 257000 , terjual:34 ,  icon:"fa-solid fa-headphones", images: '../assets/images/product/Frame 612.png', url: 'https://example.com/yoga', },   
    { productName:'S-Series Comfort Chair ', category:"Home & Lifestyle", subCategory:"Furniture", harga: 257000 , terjual:48 , discount: 25 , icon:"fa-solid fa-couch", images: '../assets/images/product/Frame 611.png', url: 'https://example.com/yoga', },   
    { productName:'S-Series Comfort Chair ', category:"Home & Lifestyle", subCategory:"Furniture", harga: 257000 , terjual:55 , discount: 25 , icon:"fa-solid fa-couch", images: '../assets/images/product/Frame 611.png', url: 'https://example.com/yoga', },   
    { productName:'S-Series Comfort Chair ', category:"Home & Lifestyle", subCategory:"Furniture", harga: 257000 , terjual:80 , discount: 25 , icon:"fa-solid fa-couch", images: '../assets/images/product/Frame 611.png', url: 'https://example.com/yoga', },   
    { productName:'S-Series Comfort Chair ', category:"Home & Lifestyle", subCategory:"Furniture", harga: 257000 , terjual:3 , discount: 25 , icon:"fa-solid fa-couch", images: '../assets/images/product/Frame 611.png', url: 'https://example.com/yoga', },   
    { productName:'S-Series Comfort Chair ', category:"Home & Lifestyle", subCategory:"Furniture", harga: 257000 , terjual:67 , discount: 25 , icon:"fa-solid fa-couch", images: '../assets/images/product/Frame 611.png', url: 'https://example.com/yoga', },   
    { productName:'S-Series Comfort Chair ', category:"Home & Lifestyle", subCategory:"Bag", harga: 257000 , terjual:69 ,  icon:"fa-solid fa-shopping-bag", images: '../assets/images/product/Frame 612.png', url: 'https://example.com/yoga', },   
    { productName:'S-Series Comfort Chair ', category:"Home & Lifestyle", subCategory:"Shirt", harga: 257000 , terjual:150 ,  icon:"fa-solid fa-shirt", images: '../assets/images/product/Frame 612.png', url: 'https://example.com/yoga', },   
    { productName:'Dumbbell ', category:"Sports & Outdoor", subCategory:"Sports", harga: 257000 , terjual:51 ,  icon:"fa-solid fa-dumbbell", images: '../assets/images/product/Frame 612.png', url: 'https://example.com/yoga', },   
    { productName:'Drug ', category:"Medicine", subCategory:"Medicine", harga: 257000 , terjual:15 ,  icon:"fa-solid fa-pills", images: '../assets/images/product/Frame 612.png', url: 'https://example.com/yoga', },   
];

export default productData;